version: '3.5'

services:
  database:
    image: backoffice-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Backoffice
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    restart: always
