services:
  database:
    image: finances
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=finances
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

volumes:
  db-volume:
